### ISSUE TITLE
OpenBSD - config.ssh.shell is invalid

### ISSUE THREAD

**Issue by abyxcos** [jcmdln/vagrant-boxes#1] opened 2022-05-30 21:24 UTC
> The configured shell (config.ssh.shell) is invalid and unable
to properly execute commands. The most common cause for this is
using a shell that is unavailable on the system. Please verify
you're using the full path to the shell and that the shell is
executable by the SSH user.

Vagrant version:  2.2.19
Vagrant backing: libvirt

Not sure how to debug this. It looks like your Vagrantfile sets the shell to /bin/ksh -l, so I assume it's complaining about something else? Ksh syntax? I can provide more info if needed.

**Comment by jcmdln** [comment] 2022-05-31 04:41
Are you building locally using packer, or using the Vagrant box I pushed to `https://app.vagrantup.com/jcmdln`? I was able to build a new OpenBSD box and run it in Vagrant so if I had to guess this is a bug from me not properly "packaging" the Vagrant box, and required values such as `config.ssh.shell = "/bin/ksh -l"` are not implicitly defined.

**Comment by jcmdln** [comment] 2022-05-31 04:43
Woops, meant to share this similar scenario I came across which supports my theory that this issue is specifically when pulling the OpenBSD box: https://github.com/hashicorp/vagrant/issues/9078#issuecomment-338323555

**Comment by abyxcos** [comment] 2022-05-31 11:15
Yup, this happens when I pull the box. I haven't tried building locally.

**Comment by jcmdln** [comment] 2022-05-31 12:05
Looks like fixing this so that pulling the OpenBSD box works as intended will involve customizing the [vagrantfile_template](https://www.packer.io/plugins/post-processors/vagrant/vagrant#vagrantfile_template). I'll look into this, but for now as a workaround you could use this repo's Vagrantfile or make your own that mimics the OpenBSD config block.

**Comment by jcmdln** [comment] 2022-05-31 12:48
I've updated the OpenBSD 7.1 box, now using `vagrant init` should work:

```sh
vagrant init jcmdln/openbsd
vagrant plugin install vagrant-libvirt
vagrant up
```

The only customization I did was to disable NFS:
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "jcmdln/openbsd"

  config.nfs.verify_installed = false
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
```

Let me know if this works for you as well and I can get the other OpenBSD boxes updated.

**Comment by jcmdln** [comment] 2022-05-31 13:40
We're talking about this elsewhere so I'll close this issue

**Closed as completed by jcmdln** 2022-05-31 13:40 UTC
Labels: bug
